##' Construct \code{qSig} object used for GESS methods
##' 
##' @title qSig constructor method
##' @rdname qSig-methods
##' @export
setGeneric("qSig", function(query, gess_method, refdb) 
  standardGeneric("qSig"))

##' Method extracts \code{tibbles} from \code{result} slots of \code{feaResult} 
##' and \code{gessResult} objects. They are generated by the GESS and FEA 
##' functions defined by \code{signatureSearch}, respectively.
##' @title Method to Extract Result Slots
##' @rdname result-methods
##' @export
setGeneric("result", function(x) standardGeneric("result"))

##' @title Extract Drug Names from feaResult
##' @rdname get_drugs-methods
##' @export
setGeneric("get_drugs", function(x) standardGeneric("get_drugs"))

setGeneric("connectivity_score_raw",
           function( experiment, query, ... ){
             standardGeneric( "connectivity_score_raw" )
})
