##' Method extracts \code{tibbles} from \code{result} slots of \code{feaResult} 
##' and \code{gessResult} objects. They are generated by the GESS and FEA 
##' functions defined by \code{signatureSearch}, respectively.
##' @title Method to Extract Result Slots
##' @rdname result-methods
##' @export
setGeneric("result", function(x) standardGeneric("result"))

##' @title Extract/Assign Drug Names for feaResult
##' @rdname drugs-methods
##' @export
setGeneric("drugs", function(x) standardGeneric("drugs"))

##' @rdname drugs-methods
##' @export
setGeneric("drugs<-", function(x, value) standardGeneric("drugs<-"))
