# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcGseaStatCumulativeBatch <- function(stats, gseaParam, pathwayScores, 
                                        pathwaysSizes, iterations, seed) {
    .Call('_signatureSearch_calcGseaStatCumulativeBatch',
          PACKAGE = 'signatureSearch', stats, gseaParam, pathwayScores, 
          pathwaysSizes, iterations, seed)
}

calcGseaStatCumulative <- function(stats, selectedStats, gseaParam) {
    .Call('_signatureSearch_calcGseaStatCumulative', 
          PACKAGE = 'signatureSearch', stats, selectedStats, gseaParam)
}

calcGseaStatBatchCpp <- function(stats, selectedGenes, geneRanks) {
    .Call('_signatureSearch_calcGseaStatBatchCpp', PACKAGE = 'signatureSearch',
          stats, selectedGenes, geneRanks)
}

